### ISSUE TITLE
How to create GSEvents for finger taps/swipes or keyboard presses?

### ISSUE THREAD

**Issue by peterhajas** [kennytm/iphone-private-frameworks#4]
Hey there,

There seems to be very little documentation available on the net about GSEvent.h. What's the easiest way to create GSEventRecords that correspond to finger taps/swipes and keyboard presses? Are they sent via GSSendSystemEvent or a different function?

Thanks for any and all help people can offer!

**Comment by kennytm** [comment]
Off-topic.

**Comment by kennytm** [comment]
(You need to continuously send many touch events for a swipe.)
